export default {
  plugins: {
    tailwindcss: {},
    autoprefixer: {},
    // PurgeCSS temporarily disabled due to CSS issues
    // ...(process.env.NODE_ENV === 'production' && {
    //   '@fullhuman/postcss-purgecss': {
    //     content: [
    //       './client/index.html',
    //       './client/src/**/*.{js,jsx,ts,tsx}',
    //     ],
    //     safelist: {
    //       // Keep essential classes
    //       standard: [
    //         /^sr-only/,
    //         /^skip-link/,
    //         /^loading/,
    //         /^loaded/,
    //         /^container-/,
    //         /^btn-/,
    //         /^nav-/,
    //         /^hero/,
    //         /^text-gradient-/,
    //         /^gradient-/,
    //         /^glass/,
    //         /^hover-/,
    //         /^animate-/,
    //         /^custom-/,
    //         // Essential Tailwind utilities
    //         /^bg-/,
    //         /^text-/,
    //         /^p-/,
    //         /^px-/,
    //         /^py-/,
    //         /^pt-/,
    //         /^pb-/,
    //         /^pl-/,
    //         /^pr-/,
    //         /^m-/,
    //         /^mx-/,
    //         /^my-/,
    //         /^mt-/,
    //         /^mb-/,
    //         /^ml-/,
    //         /^mr-/,
    //         /^w-/,
    //         /^h-/,
    //         /^min-/,
    //         /^max-/,
    //         /^flex/,
    //         /^grid/,
    //         /^block/,
    //         /^inline-/,
    //         /^hidden/,
    //         /^relative/,
    //         /^absolute/,
    //         /^fixed/,
    //         /^sticky/,
    //         /^top-/,
    //         /^bottom-/,
    //         /^left-/,
    //         /^right-/,
    //         /^z-/,
    //         /^border/,
    //         /^rounded/,
    //         /^shadow/,
    //         /^opacity/,
    //         /^transition/,
    //         /^transform/,
    //         /^scale/,
    //         /^rotate/,
    //         /^translate/,
    //         /^skew/,
    //       ],
    //       deep: [
    //         /^:hover/,
    //         /^:focus/,
    //         /^:active/,
    //         /^:visited/,
    //         /^:disabled/,
    //         /^:checked/,
    //         /^:required/,
    //         /^:valid/,
    //         /^:invalid/,
    //         /^:first-child/,
    //         /^:last-child/,
    //         /^:nth-child/,
    //         /^:before/,
    //         /^:after/,
    //         /^::before/,
    //         /^::after/,
    //         /^::placeholder/,
    //         /^::selection/,
    //       ],
    //     },
    //     variables: true,
    //     keyframes: true,
    //     fontFace: true,
    //   },
    // }),
  },
}
